Scripts/CognitoTrustPolicy.json, Scripts/ConfigureAwsForExperiment.sh, Scripts/ParticipantPermissionPolicy.json, Sensus.Android/Resources/Resource.Designer.cs, Sensus.Android/Sensus.Android.csproj, Sensus.Android/packages.config, Sensus.iOS/Sensus.iOS.csproj, Sensus.iOS/packages.config, SensusService/DataStores/Remote/AmazonS3RemoteDataStore.cs
Replace commercial AWS S3 component with free Xamarin SDK.
=> Xamarin s3 component

Sensus.Android/Sensus.Android.csproj, Sensus.iOS/Entitlements.plist, Sensus.iOS/Info.plist, Sensus.iOS/Probes/Health/iOSHealth.cs, Sensus.iOS/Sensus.iOS.csproj, Sensus.iOS/packages.config, SensusService/Probes/Health/HealthDatum.cs, SensusService/Probes/Health/HealthProbe.cs, SensusService/SensusService.projitems
Added HealthKit functionality for reviewing
=> Added HealthKit Functionality

Sensus.Shared.Tests/Sensus.Shared/Concurrent/IConcurrentTests.cs
GitHub Works now :). Closes #275. 
This test is a lot better. We now determine if a deadlock happened by checking to see if all expected items are added to the test array. If they aren't then we assume the synchronize action didn't finish which would be indicative of a deadlock.
I looked at the other tests too, and I think there could still be a similar problem with the above IsThreadSafe checks. However, the solution there didn't immediately pop out at me, and since the test seems to function as desired thus far, I decided to leave it for another day.
=> Better unit tests design

Sensus.Shared.Tests/Sensus.Shared/Concurrent/IConcurrentTests.cs
Just improving our tests so that it is more clear when things break what it is exactly that is broken. 
I've confirmed the new tests run locally, on Android and on iOS.
=> Better concurrent tests

Sensus.Shared/UI/PendingScriptsPage.cs
@MatthewGerber This is working on Android. I'm having trouble with Apple provisioning profiles and haven't been able to test on iOS. I don't see any reason it wouldn't work on iOS too (the documentation suggests the only platform-specific code is the `isDestructive` property on line 103 of `PendingScriptsPage`), but I wanted to let you know in case you wanted to test it on your device.
=> Add option to delete pending scripts. Addresses issue #296.

ProtocolBuilder/assets/js/scripts.js, ProtocolBuilder/index.html
These changes are already on  [the web site](http://boukhechba.com/sensus/)
=> Adding data storage options and All the probes except : Beacons, Facebook, and Scripted interactions

Sensus.Shared/UI/ProtocolsPage.cs
Add on-demand remote data store write. #453
=> Add on-demand remote data store write. #453

Sensus.Shared/Probes/User/Scripts/Script.cs, Sensus.Shared/SensusServiceHelper.cs, Sensus.Shared/UI/PendingScriptsPage.cs
In order to display the scripts in order of the birthdate I used LINQ to get a sorted list of the scripts and added them to a new ConcurrentObservableCollection.  I then added that to the ListViews ItemSource.
=> #473 Sort surveys by displayed timestamp.

Sensus.Android/AndroidSensusServiceHelper.cs, Sensus.Android/Probes/Device/AndroidPowerConnectionChange.cs, Sensus.Android/Probes/Device/AndroidPowerConnectionChangeBroadcastReceiver.cs, Sensus.Android/Sensus.Android.csproj, Sensus.Shared.Tests/Classes/TestSensusServiceHelper.cs, Sensus.Shared/DataStores/Remote/RemoteDataStore.cs, Sensus.Shared/Probes/Device/PowerConnectionChange.cs, Sensus.Shared/Sensus.Shared.projitems, Sensus.Shared/SensusServiceHelper.cs, Sensus.iOS.Shared/Probes/Context/iOSPowerConnectionChange.cs, Sensus.iOS.Shared/Probes/iOSPowerConnectionChange.cs, Sensus.iOS.Shared/Sensus.iOS.Shared.projitems, Sensus.iOS/iOSSensusServiceHelper.cs, Sensus.sln
=> Ac power connect

Sensus.Android.Shared/Probes/Context/AndroidBluetoothClientGattCallback.cs, Sensus.Android.Shared/Probes/Context/AndroidBluetoothClientScannerCallback.cs, Sensus.Android.Shared/Probes/Context/AndroidBluetoothDeviceProximityProbe.cs, Sensus.Android.Shared/Probes/Context/AndroidBluetoothServerAdvertisingCallback.cs, Sensus.Android.Shared/Probes/Context/AndroidBluetoothServerGattCallback.cs, Sensus.Shared/Probes/Context/BluetoothDeviceProximityProbe.cs, Sensus.iOS.Shared/Probes/Context/iOSBluetoothDeviceProximityProbe.cs, Sensus.iOS.Shared/Probes/Context/iOSBluetoothDeviceProximityProbeCentralManagerDelegate.cs
=> Fix BLE encounters

Sensus.Android.Shared/AndroidSensusServiceHelper.cs, Sensus.Android.Shared/Probes/Apps/AndroidKeystrokeProbe.cs, Sensus.Android.Shared/Probes/Apps/AndroidKeystrokeService.cs, Sensus.Android.Shared/Probes/Network/AndroidWlanBroadcastReceiver.cs, Sensus.Android.Shared/Sensus.Android.Shared.projitems, Sensus.Android.Tests.AppCenter/Sensus.Android.Tests.AppCenter.csproj, Sensus.Android/AndroidMainActivity.cs, Sensus.Android/Properties/AndroidManifest.xml, Sensus.Shared/Probes/Apps/KeystrokeDatum.cs, Sensus.Shared/Probes/Apps/KeystrokeProbe.cs, Sensus.Shared/Probes/Network/WlanDatum.cs, Sensus.Shared/Sensus.Shared.projitems, Sensus.iOS.Tests.AppCenter/Sensus.iOS.Tests.AppCenter.csproj, Sensus.iOS.Tests/Sensus.iOS.Tests.csproj, Sensus.iOS/Sensus.iOS.csproj, Sensus.sln
Added Keystroke probe and Wlan signal strength. Both work only for Android.
=> Mehdi test

Sensus.Android.Shared/Probes/Network/AndroidWlanBroadcastReceiver.cs, Sensus.Shared/Probes/Device/ListeningPowerConnectProbe.cs, Sensus.Shared/Probes/Device/PowerConnectDatum.cs, Sensus.Shared/Sensus.Shared.projitems
This probe records a datum each time the phone is either plugged into (true) or removed from (false) an external power source.
=> Add Power Connect Probe

DocFX/docfx.json, Sensus.Android.Shared/AndroidSensusServiceHelper.cs, Sensus.Android.Shared/Probes/Apps/AndroidKeystrokeProbe.cs, Sensus.Android.Shared/Probes/Apps/AndroidKeystrokeService.cs, Sensus.Android.Shared/Probes/Network/AndroidWlanBroadcastReceiver.cs, Sensus.Android.Shared/Sensus.Android.Shared.projitems, Sensus.Android.Tests.AppCenter/Sensus.Android.Tests.AppCenter.csproj, Sensus.Android/AndroidMainActivity.cs, Sensus.Android/Properties/AndroidManifest.xml, Sensus.Shared/Probes/Apps/KeystrokeDatum.cs, Sensus.Shared/Probes/Apps/KeystrokeProbe.cs, Sensus.Shared/Probes/Device/ListeningPowerConnectProbe.cs, Sensus.Shared/Probes/Device/PowerConnectDatum.cs, Sensus.Shared/Probes/Network/WlanDatum.cs, Sensus.Shared/Sensus.Shared.projitems, Sensus.iOS.Tests.AppCenter/Sensus.iOS.Tests.AppCenter.csproj, Sensus.iOS.Tests/Sensus.iOS.Tests.csproj, Sensus.iOS/Sensus.iOS.csproj, Sensus.sln, docs/manifest.json
Add keystroke probe
Add Power connect probe
=> Accessibility service

Sensus.Android.Shared/Probes/Communication/AndroidSmsIncomingBroadcastReceiver.cs, Sensus.Android.Shared/Probes/Communication/AndroidSmsOutgoingObserver.cs, Sensus.Android.Shared/Probes/Communication/AndroidSmsProbe.cs, Sensus.Android.Shared/Probes/Communication/AndroidTelephonyProbe.cs, Sensus.Android.Tests.AppCenter/Sensus.Android.Tests.AppCenter.csproj, Sensus.Android.Tests.AppCenter/app.config, Sensus.Android.Tests.AppCenter/packages.config, Sensus.Android.Tests/Sensus.Android.Tests.csproj, Sensus.Android.Tests/app.config, Sensus.Android.Tests/packages.config, Sensus.Android/Properties/AndroidManifest.xml, Sensus.Android/Sensus.Android.csproj, Sensus.Android/app.config, Sensus.Android/packages.config, Sensus.Shared/Probes/Communication/SmsDatum.cs, Sensus.Shared/Probes/Communication/TelephonyDatum.cs, Sensus.Shared/SensusServiceHelper.cs, Sensus.iOS.Tests.AppCenter/Sensus.iOS.Tests.AppCenter.csproj, Sensus.iOS.Tests.AppCenter/app.config, Sensus.iOS.Tests.AppCenter/packages.config, Sensus.iOS.Tests/Sensus.iOS.Tests.csproj, Sensus.iOS.Tests/app.config, Sensus.iOS.Tests/packages.config, Sensus.iOS/Sensus.iOS.csproj, Sensus.iOS/app.config, Sensus.iOS/packages.config
Correlate phone numbers with contacts list #782
=> Contact phone numbers

Sensus.Android.Shared/Notifications/ForegroundServiceNotificationActionReceiver.cs, Sensus.Shared/UI/PauseProtocolsPage.cs, Sensus.Shared/UI/ProtocolsPage.cs
#779 Pull this if you wanted pause and snooze split into two options
=> split snooze and pause #779

Sensus.Android.Shared/Probes/Context/AndroidBluetoothClientScannerCallback.cs, Sensus.Android.Shared/Probes/Context/AndroidBluetoothDevice.cs, Sensus.Android.Shared/Probes/Context/AndroidBluetoothDeviceProximityProbe.cs, Sensus.Android.Shared/Probes/Context/AndroidBluetoothDeviceReceiver.cs, Sensus.Android.Shared/Sensus.Android.Shared.projitems, Sensus.Shared.NuGet/Probes/Context/IBluetoothDeviceProximityDatum.cs, Sensus.Shared/Probes/Context/BluetoothDeviceProximityDatum.cs, Sensus.Shared/Probes/Context/BluetoothDeviceProximityProbe.cs, Sensus.Shared/Probes/Context/BluetoothScanModes.cs, Sensus.Shared/Sensus.Shared.projitems, Sensus.iOS.Shared/Probes/Context/iOSBluetoothDeviceProximityProbe.cs, Sensus.iOS.Shared/Probes/Context/iOSBluetoothDeviceProximityProbeCentralManagerDelegate.cs, Sensus.sln
=> bluetooth solution

Sensus.Android.Shared/Probes/Communication/AndroidSmsIncomingBroadcastReceiver.cs, Sensus.Android.Shared/Probes/Communication/AndroidSmsOutgoingObserver.cs, Sensus.Android.Shared/Probes/Communication/AndroidTelephonyProbe.cs, Sensus.Shared/Probes/Communication/SmsDatum.cs, Sensus.Shared/Probes/Communication/TelephonyDatum.cs
=> 782 correlate phonenumbers with contact list

Sensus.Shared/UI/PauseProtocolsPage.cs
Fix for #779. This was due to selecting a time in the past. Past dates are disabled. Times that would result in a date/time in the past snap to a minimum snooze time of 1 minute.
=> Snooze #779

Sensus.Android.Shared/Probes/Apps/AndroidCalendarProbe.cs, Sensus.Shared/Probes/Apps/CalendarProbe.cs, Sensus.iOS.Shared/Probes/Apps/iOSCalendarProbe.cs
#783 Added LastPollTime to the calendar probes to collect all events since the last poll
=> #783 add calendar probe

Sensus.Android.Shared/Probes/Apps/AndroidImageFileObserver.cs, Sensus.Android.Shared/Probes/Apps/AndroidImageMetadataProbe.cs, Sensus.Shared/Probes/Apps/ImageMetadataDatum.cs, Sensus.Shared/Probes/Apps/ImageMetadataProbe.cs, Sensus.iOS.Shared/Probes/Apps/iOSImageMetadataProbe.cs, Sensus.iOS.Shared/Probes/Apps/iOSPhotoLibraryChangeObserver.cs
#784 The iOS image metadata probe is implemented. The Android probe remains mostly unchanged from before with the exception of moving some code that could be shared into the base probe.
=> #784 Image metadata

Sensus.Shared/Sensus.Shared.projitems, Sensus.Shared/UI/Inputs/TimeInput.cs
=> Time picker

Sensus.Shared/Probes/User/Scripts/ScriptDatum.cs, Sensus.Shared/Probes/User/Scripts/ScriptRunner.cs, Sensus.Shared/Sensus.Shared.projitems, Sensus.Shared/UI/PendingScriptsPage.cs, Sensus.Shared/UI/ProtocolsPage.cs, Sensus.Shared/UI/RunScriptsPage.cs, Sensus.Shared/UI/UserInitiatedScriptsPage.cs
#804 The LM guys were interested in this and wanted to know when you merged it in so they could try it out. I had some ideas while doing this but I didn't implement them, so they might be things to consider for later.
- I wasn't sure if the ScriptDatum should record whether a script was run manually or the normal way.
-  It also might be useful to allow a configurable "cooldown" on the scripts for running them manually so people can't just run them over and over again.
=> #804 User initiated surveys

Sensus.Android.Shared/Probes/Apps/AndroidApplicationUsageProbe.cs, Sensus.Android.Shared/Probes/Apps/ApplicationUsageDatum.cs, Sensus.Android.Shared/Sensus.Android.Shared.projitems, Sensus.Android/Properties/AndroidManifest.xml
#818 I've added a probe that queries for application events (Backgrounded, Foregrounded, configuration changes, etc.) I'm not sure if this is exactly what is desired.
The UsageStatsManager also has a query for usage statistics and I started out making a probe for both, but the usage statistics were unreliable due to the way the aggregation intervals and our polling times work. It's possible that if the probe had a poll time for over a day that it might work. If we want to look into this it is easy enough to add it back.
=> #818 App usage

Sensus.Shared/Probes/Apps/ImageMetadataDatum.cs, Sensus.Shared/Probes/Location/VisitDatum.cs, Sensus.Shared/Probes/Location/VisitProbe.cs, Sensus.Shared/Sensus.Shared.projitems, Sensus.iOS.Shared/Probes/Location/VisitDatum.cs, Sensus.iOS.Shared/Probes/Location/iOSVisitProbe.cs, Sensus.iOS.Shared/Sensus.iOS.Shared.projitems
#750 visit monitoring is working
=> #750 visit monitoring

Sensus.Shared/Probes/User/Scripts/ScriptRunner.cs
#864 a fix for script callbacks
=> #864 Script callbacks

Sensus.iOS/Info.plist
=> Update iOS app version

Sensus.iOS/Sensus.iOS.csproj
Reverts predictive-technology-laboratory/sensus#869
=> Revert "Update Sensus.iOS.csproj"

Sensus.Android.Shared/Probes/Apps/AndroidAccessibilityService.cs, Sensus.Android.Shared/Probes/Apps/AndroidApplicationUsageManager.cs
=> #878 partial permission rollback

Sensus.Shared/Probes/User/Scripts/ScriptRunner.cs, Sensus.Shared/UI/ScriptInputsPage.cs, Sensus.Shared/UI/ScriptRunnersPage.cs
#861 Added Copy menu item for Scripts and inputs. Input groups already had one.
I noticed while working on this that Sensus does not work correctly with the new Dark Mode in iOS. Sensus' text stays black on the black background from Dark Mode.
=> #861 Copy scripts

Sensus.Shared/UI/Inputs/DateTimeInput.cs, Sensus.Shared/UI/Inputs/TimeInput.cs
#892 fixed the issue. the timepicker wasn't being marked as complete due to bad logic on my part.
I also fixed an issue with the text coloring to make it work like the other inputs.
=> #892 time picker issue

Sensus.Shared/UI/ProbesViewPage.cs
=> #889 estimote beacon probe fix

Sensus.Shared.NuGet/Sensus.Shared.NuGet.csproj, Sensus.iOS.Shared/Callbacks/iOSCallbackScheduler.cs, Sensus.iOS.Shared/Callbacks/iOSTimerCallbackScheduler.cs, Sensus.iOS.Shared/Sensus.iOS.Shared.projitems, Sensus.iOS/AppDelegate.cs
=> Remove silent notifications

Sensus.Shared/UI/Inputs/DateTimeInput.cs, Sensus.Shared/UI/Inputs/TimeInput.cs
=> timepicker and datepicker inputs

Sensus.iOS.Shared/Probes/Location/iOSVisitProbe.cs
#886 I got multiple visits between yesterday and this morning, so it looks like this is working now.
=> #886 visit probe issue

Sensus.Shared/Protocol.cs, Sensus.Shared/ProtocolStateDatum.cs, Sensus.Shared/Sensus.Shared.projitems
=> #901 Protocol state datum

Sensus.iOS.Shared/Callbacks/iOSTimerCallbackScheduler.cs
=> Survey issue

Sensus.Android.Shared/Probes/Apps/AndroidKeystrokeProbe.cs, Sensus.Shared/Anonymization/AnonymizedJsonContractResolver.cs, Sensus.Shared/Anonymization/Anonymizers/RegExAnonymizer.cs, Sensus.Shared/UI/ProbePage.cs
#893 Fixed anonymizer serialization to preserve anonymizer settings when a protocol is serialized. I think this change will cause existing protocols to lose their anonymizers.
=> #893 fixed anonymizer serialization

Sensus.Shared/Anonymization/AnonymizedJsonContractResolver.cs, Sensus.Shared/Anonymization/Anonymizers/Anonymizer.cs, Sensus.Shared/Anonymization/Anonymizers/RegExAnonymizer.cs
=> #893 support legacy protocol anonymizer serialization

ExampleSensingAgent.Shared/ExampleCompassSensingAgent.cs, ExampleSensingAgent.Shared/ExampleSensingAgent.Shared.projitems, Sensus.Shared.NuGet/Adaptation/SensingAgent.cs
Mehdi,
Here is a new example sensing agent as we discussed last week. My major purpose in this request is simply to show my pull workflow and coding style. The agent itself is very simple and based around a single compass probe (we will certainly want to use more probe types as part of the capstone). 
Let me know what you think and any changes you'd like to see with my coding style.
Thanks
=> New Example Sensing Agent

ExampleSensingAgent.Shared/ExampleCapstoneAccelerationSensingAgent.cs, ExampleSensingAgent.Shared/ExampleSensingAgent.Shared.projitems, Sensus.Android/Sensus.Android.csproj, Sensus.Android/packages.config, Sensus.Shared.NuGet/Adaptation/SensingAgent.cs, Sensus.Shared/Probes/Movement/LinearAccelerationDatum.cs, Sensus.iOS.Shared/Probes/Movement/iOSAccelerometerProbe.cs, Sensus.iOS/Sensus.iOS.csproj, Sensus.iOS/packages.config, Sensus.sln
This pull request contains the initial developed code for the capstone sensing project. As of yet this code has only been tested via emulator until a new cable arrives to enable on device debugging.
=> Capstone active sensing

Sensus.Shared/Anonymization/AnonymizedJsonContractResolver.cs, Sensus.Shared/Protocol.cs
=> #726 Anonymizer summary

Sensus.Shared/Sensus.Shared.projitems, Sensus.Shared/UI/InputGroupPage.cs, Sensus.Shared/UI/Inputs/Input.cs, Sensus.Shared/UI/Inputs/TimerInput.cs
=> #862 Timer input

ExampleSensingAgent.Shared/ExampleCapstoneAccelerationSensingAgent.cs
This pull request includes two changes:
1. A small change to avoid bad data in feature calculation. 
2. A small change to sensing control so that it doesn't force device to stay awake.
=> small fixes after testing on phone

Sensus.Shared/Protocol.cs
#726 Changed format and fixed properties on base Datum not showing up.
=> #726 anonymization summary

Sensus.Shared/UI/InputGroupPage.cs, Sensus.Shared/UI/Inputs/Input.cs, Sensus.Shared/UI/Inputs/MediaInput.cs, Sensus.Shared/UI/UiProperties/MediaPickerUiProperty.cs
=> #860 refactor media inputs

Sensus.Shared/Probes/User/Scripts/ScriptRunner.cs, Sensus.sln
Fixed duplicate surveys. Changed ScriptRunner.ScheduleScriptRunsAsync() to skip rescheduling a window when the survey was recently run within that window.
=> duplicate surveys

Scripts/ConfigureAWS/ec2-push-notifications/send-push-notifications.py
Converted send-push-notifications.sh to python
=> Python conversion

Sensus.Shared/SensusServiceHelper.cs, Sensus.Shared/UI/App.xaml, Sensus.Shared/UI/UserInitiatedScriptsPage.cs, Sensus.iOS.Shared/UI/iOSVideoRenderer.cs
=> Enhanced surveys

Sensus.Shared/SensusServiceHelper.cs
sensusservicehelper - build_id
=> sensusservicehelper - build_id
